### ISSUE TITLE
little help

### ISSUE THREAD

**Issue by SoccerCashUK** [MauroAndretta/AIFootballPreictions#4]
Hi everything works until i use python scripts/make_predictions.py --models_dir models --data_dir data/processed --output_file final_predictions.txt --json_competitions data/next_matches.json 

then error
C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main>python scripts/make_predictions.py --models_dir models --data_dir data/processed --output_file final_predictions.txt --json_competitions data/next_matches.json
usage: make_predictions.py [-h] --input_leagues_models_dir INPUT_LEAGUES_MODELS_DIR --input_data_predict_dir
                           INPUT_DATA_PREDICT_DIR --final_predictions_out_file FINAL_PREDICTIONS_OUT_FILE
                           --json_competitions JSON_COMPETITIONS
make_predictions.py: error: the following arguments are required: --input_leagues_models_dir, --input_data_predict_dir, --final_predictions_out_file

James

**Comment by MauroAndretta** [comment]
Your command is not correct!
Please use this instead!
`python scripts/make_predictions.py --input_leagues_models_dir models --input_data_predict_dir data/processed --final_predictions_out_file data/final_predictions.txt --json_competitions data/next_matches.json`

James please, consider to support this project with a star  💕

**Comment by SoccerCashUK** [comment]
ok tried that this is what i get

----------------------------------

Making predictions for E0...

Loaded model and data for E0.
Predicting matches for E0...
Predictions made for E0.
----------------------------------

Making predictions for I1...

Loaded model and data for I1.
Predicting matches for I1...
Predictions made for I1.
----------------------------------

Making predictions for D1...

Loaded model and data for D1.
Predicting matches for D1...
Predictions made for D1.
----------------------------------

Making predictions for SP1...

Loaded model and data for SP1.
Predicting matches for SP1...
Traceback (most recent call last):
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\make_predictions.py", line 209, in <module>
    main(args.input_leagues_models_dir, args.input_data_predict_dir, args.final_predictions_out_file, args.json_competitions)
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\make_predictions.py", line 192, in main
    league_section = make_predictions(league, league_model, league_data, competitions)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\Downloads\AIFootballPreictions-main\AIFootballPreictions-main\scripts\make_predictions.py", line 147, in make_predictions
    prediction = league_model.predict(X_test)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_voting.py", line 440, in predict
    maj = np.argmax(self.predict_proba(X), axis=1)
                    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_voting.py", line 481, in predict_proba
    self._collect_probas(X), axis=0, weights=self._weights_not_none
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\ensemble\_voting.py", line 456, in _collect_probas
    return np.asarray([clf.predict_proba(X) for clf in self.estimators_])
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1431, in predict_proba
    return super()._predict_proba_lr(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_base.py", line 397, in _predict_proba_lr
    prob = self.decision_function(X)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_base.py", line 363, in decision_function
    X = self._validate_data(X, accept_sparse="csr", reset=False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py", line 633, in _validate_data
    out = check_array(X, input_name="X", **check_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py", line 1064, in check_array
    _assert_all_finite(
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py", line 123, in _assert_all_finite
    _assert_all_finite_element_wise(
  File "C:\Users\Iphon\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py", line 172, in _assert_all_finite_element_wise
    raise ValueError(msg_err)
ValueError: Input X contains NaN.
LogisticRegression does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
